-- Status e vendedores da agenda passam a ser editados na propria agenda (Diretoria e
-- Administrador), como os adesivadores.

-- Os status. Os seis do sistema (chave preenchida) tem regra por tras - executando,
-- concluido... - e so mudam de nome e cor. Os criados na agenda (chave nula) sao
-- etiquetas de um servico que ainda nao comecou, e podem ser removidos.
CREATE TABLE status_agenda (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave  VARCHAR(20),
    nome   VARCHAR(40) NOT NULL,
    cor    VARCHAR(7)  NOT NULL,
    ordem  INTEGER     NOT NULL,
    CONSTRAINT uk_status_agenda_chave UNIQUE (chave)
);

INSERT INTO status_agenda (chave, nome, cor, ordem) VALUES
    ('PROGRAMADO', 'Programado', '#94a3b8', 1),
    ('EM_PATIO',   'Em pátio',   '#0284c7', 2),
    ('EXECUTANDO', 'Executando', '#d97706', 3),
    ('CONCLUIDO',  'Concluído',  '#16a34a', 4),
    ('NAO_VEIO',   'Não veio',   '#dc2626', 5),
    ('EXTERNO',    'Externo',    '#7c3aed', 6);

-- O status criado na agenda que o card tem agora (nulo: vale o status do sistema).
ALTER TABLE agendamentos ADD COLUMN etiqueta_id BIGINT REFERENCES status_agenda (id);

-- Os vendedores da agenda: o codigo (a letra do cronograma) e o que fica gravado no card.
-- A lista inicial vem dos usuarios do comercial (V14).
CREATE TABLE vendedores_agenda (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(5)  NOT NULL,
    nome   VARCHAR(60) NOT NULL,
    ativo  BOOLEAN     NOT NULL,
    CONSTRAINT uk_vendedores_agenda_codigo UNIQUE (codigo)
);
