-- As secoes que cada perfil traz prontas passam a ser editadas pelo Administrador
-- (Administracao -> Permissoes). Comeca com o que cada perfil ja podia. O Administrador
-- tem todas sempre: nao da para ele se trancar para fora.
CREATE TABLE perfil_secoes (
    perfil_id INTEGER     NOT NULL REFERENCES perfis (id) ON DELETE CASCADE,
    secao     VARCHAR(40) NOT NULL,
    PRIMARY KEY (perfil_id, secao)
);

INSERT INTO perfil_secoes (perfil_id, secao)
SELECT p.id, s.secao
FROM perfis p
JOIN (
    SELECT 'VENDEDOR' AS perfil, 'PAINEL' AS secao
    UNION ALL SELECT 'VENDEDOR', 'PAINEL_ADESIVADORES'
    UNION ALL SELECT 'VENDEDOR', 'PAINEL_ACABAMENTO'
    UNION ALL SELECT 'VENDEDOR', 'AGENDA_VER'
    UNION ALL SELECT 'VENDEDOR', 'AGENDA_EDITAR'
    UNION ALL SELECT 'VENDEDOR', 'PATIO_PRATELEIRA'
    UNION ALL SELECT 'VENDEDOR', 'CONSULTA'
    UNION ALL SELECT 'VENDEDOR', 'CRIAR_OS'
    UNION ALL SELECT 'DIRETORIA', 'PAINEL'
    UNION ALL SELECT 'DIRETORIA', 'PAINEL_ADESIVADORES'
    UNION ALL SELECT 'DIRETORIA', 'PAINEL_ACABAMENTO'
    UNION ALL SELECT 'DIRETORIA', 'AGENDA_VER'
    UNION ALL SELECT 'DIRETORIA', 'AGENDA_EDITAR'
    UNION ALL SELECT 'DIRETORIA', 'AGENDA_LEGENDA'
    UNION ALL SELECT 'DIRETORIA', 'PATIO_PRATELEIRA'
    UNION ALL SELECT 'DIRETORIA', 'CONSULTA'
    UNION ALL SELECT 'DIRETORIA', 'CRIAR_OS'
    UNION ALL SELECT 'DIRETORIA', 'PRODUTIVIDADE'
    UNION ALL SELECT 'DIRETORIA', 'RELATORIO'
    UNION ALL SELECT 'FINANCEIRO', 'PAINEL'
    UNION ALL SELECT 'FINANCEIRO', 'PAINEL_ADESIVADORES'
    UNION ALL SELECT 'FINANCEIRO', 'PAINEL_ACABAMENTO'
) s ON s.perfil = p.nome;
