-- Pausas dos projetos: o adesivador pausa e retoma o servico pela Minha agenda. Cada pausa
-- guarda o inicio e o fim (aberta enquanto fim for nulo). A pausa e do servico inteiro:
-- servico_id e a chave do conjunto de partes (grupo_id do card, ou o proprio id dele).
CREATE TABLE pausas_projeto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id  BIGINT NOT NULL,
    inicio      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    fim         TIMESTAMP(6) WITH TIME ZONE,
    pausado_por INTEGER REFERENCES usuarios (id) ON DELETE SET NULL
);

CREATE INDEX idx_pausas_projeto_servico ON pausas_projeto (servico_id);
