-- Schema de partida do OS Tracker, transcrito do que o Hibernate (ddl-auto: update)
-- tinha gerado ate aqui. Portavel entre H2 (modo PostgreSQL) e PostgreSQL.
--
-- Num banco que ja existia antes do Flyway, esta migracao NAO roda: o Flyway marca a
-- versao 1 como linha de base (baseline-on-migrate) e segue das seguintes.

CREATE TABLE perfis (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    CONSTRAINT uk_perfis_nome UNIQUE (nome)
);

CREATE TABLE setores (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo BOOLEAN NOT NULL,
    nome  VARCHAR(50) NOT NULL,
    CONSTRAINT uk_setores_nome UNIQUE (nome)
);

CREATE TABLE usuarios (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo      BOOLEAN NOT NULL,
    email      VARCHAR(100) NOT NULL,
    nome       VARCHAR(100) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil_id  INTEGER NOT NULL REFERENCES perfis (id),
    setor_id   INTEGER REFERENCES setores (id),
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE transicoes_permitidas (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setor_destino VARCHAR(50) NOT NULL,
    setor_origem  VARCHAR(50)
);

CREATE TABLE ordens_servico (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancelada           BOOLEAN NOT NULL,
    cliente             VARCHAR(120),
    criado_em           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    motivo_cancelamento TEXT,
    numero_os_erp       VARCHAR(50) NOT NULL,
    criado_por          INTEGER NOT NULL REFERENCES usuarios (id)
);
CREATE INDEX idx_os_numero ON ordens_servico (numero_os_erp);

CREATE TABLE fluxos_os (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encerrado           BOOLEAN NOT NULL,
    encerrado_em        TIMESTAMP(6) WITH TIME ZONE,
    entrou_no_setor_em  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    identificador_fluxo VARCHAR(50) NOT NULL,
    motivo_cancelamento TEXT,
    recebido_em         TIMESTAMP(6) WITH TIME ZONE,
    status_atual        VARCHAR(50) NOT NULL,
    os_id               INTEGER NOT NULL REFERENCES ordens_servico (id),
    recebido_por_id     INTEGER REFERENCES usuarios (id),
    setor_anterior_id   INTEGER REFERENCES setores (id),
    setor_atual_id      INTEGER NOT NULL REFERENCES setores (id)
);
CREATE INDEX idx_fluxo_setor ON fluxos_os (setor_atual_id, encerrado);

CREATE TABLE eventos_movimentacao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    observacao       TEXT,
    tipo_evento      VARCHAR(30) NOT NULL,
    fluxo_id         INTEGER NOT NULL REFERENCES fluxos_os (id),
    setor_destino_id INTEGER NOT NULL REFERENCES setores (id),
    setor_origem_id  INTEGER REFERENCES setores (id),
    usuario_id       INTEGER NOT NULL REFERENCES usuarios (id)
);
CREATE INDEX idx_eventos_fluxo ON eventos_movimentacao (fluxo_id, data_hora);

CREATE TABLE adesivadores (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo      BOOLEAN NOT NULL,
    nome       VARCHAR(60) NOT NULL,
    ordem      INTEGER NOT NULL,
    tipo       VARCHAR(20) NOT NULL,
    usuario_id INTEGER REFERENCES usuarios (id)
);

CREATE TABLE agendamentos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atualizado_em   TIMESTAMP(6) WITH TIME ZONE,
    criado_em       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    data            DATE NOT NULL,
    descricao       VARCHAR(200) NOT NULL,
    duracao_slots   INTEGER NOT NULL,
    observacao      TEXT,
    score           NUMERIC(6, 2),
    slot_inicio     INTEGER NOT NULL,
    status          VARCHAR(20) NOT NULL,
    vendedor_codigo VARCHAR(5),
    adesivador_id   INTEGER NOT NULL REFERENCES adesivadores (id),
    criado_por      INTEGER REFERENCES usuarios (id),
    os_id           INTEGER REFERENCES ordens_servico (id),
    horas_estimadas NUMERIC(5, 2),
    tipo            VARCHAR(20),
    concluido_em    TIMESTAMP(6) WITH TIME ZONE,
    iniciado_em     TIMESTAMP(6) WITH TIME ZONE
);
CREATE INDEX idx_agendamento_data ON agendamentos (data, adesivador_id, slot_inicio);
CREATE INDEX idx_agendamento_os ON agendamentos (os_id);
