-- Pilha do "desfazer" da agenda. Antes ficava na memoria e sumia quando a aplicacao
-- reiniciava. Cada linha e o retrato de um trecho da agenda antes de uma alteracao.
CREATE TABLE historico_agenda (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     INTEGER NOT NULL REFERENCES usuarios (id),
    descricao      VARCHAR(250) NOT NULL,
    adesivador_ids VARCHAR(200) NOT NULL,
    inicio         DATE NOT NULL,
    fim            DATE NOT NULL,
    linhas         TEXT NOT NULL,
    criado_em      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_historico_usuario ON historico_agenda (usuario_id, id);
