-- Feriados: dias em que a empresa nao abre. Nao contam no tempo das OS (horario comercial).
CREATE TABLE feriados (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data      DATE        NOT NULL UNIQUE,
    descricao VARCHAR(80) NOT NULL
);

-- Nacionais de 2026 e 2027, com Carnaval e Corpus Christi (pontos facultativos que a
-- maioria das empresas emenda). Municipais e estaduais se cadastram na Administracao.
INSERT INTO feriados (data, descricao) VALUES
    (DATE '2026-01-01', 'Confraternizacao Universal'),
    (DATE '2026-02-16', 'Carnaval'),
    (DATE '2026-02-17', 'Carnaval'),
    (DATE '2026-04-03', 'Sexta-feira Santa'),
    (DATE '2026-04-21', 'Tiradentes'),
    (DATE '2026-05-01', 'Dia do Trabalho'),
    (DATE '2026-06-04', 'Corpus Christi'),
    (DATE '2026-09-07', 'Independencia do Brasil'),
    (DATE '2026-10-12', 'Nossa Senhora Aparecida'),
    (DATE '2026-11-02', 'Finados'),
    (DATE '2026-11-15', 'Proclamacao da Republica'),
    (DATE '2026-11-20', 'Consciencia Negra'),
    (DATE '2026-12-25', 'Natal'),
    (DATE '2027-01-01', 'Confraternizacao Universal'),
    (DATE '2027-02-08', 'Carnaval'),
    (DATE '2027-02-09', 'Carnaval'),
    (DATE '2027-03-26', 'Sexta-feira Santa'),
    (DATE '2027-04-21', 'Tiradentes'),
    (DATE '2027-05-01', 'Dia do Trabalho'),
    (DATE '2027-05-27', 'Corpus Christi'),
    (DATE '2027-09-07', 'Independencia do Brasil'),
    (DATE '2027-10-12', 'Nossa Senhora Aparecida'),
    (DATE '2027-11-02', 'Finados'),
    (DATE '2027-11-15', 'Proclamacao da Republica'),
    (DATE '2027-11-20', 'Consciencia Negra'),
    (DATE '2027-12-25', 'Natal');
